### PR TITLE
intel_apl_adsp: Move files from Zephyr xtensa board

### PR DESCRIPTION
**Pull request by finikorg**
Move Tensilica copyrighted files to xtensa HAL.

### CODE REVIEW

**Comment by finikorg** [comment]
@jhedberg

**Comment by jhedberg** [comment]
@finikorg you might want to elaborate a bit more in the commit message, e.g. that these are from the xtensa HAL originally (so this is a more natural place for them) and that it also resolves the license issue with these being MIT rather than Apache 2 licensed.

**Comment by finikorg** [comment]
> @finikorg you might want to elaborate a bit more in the commit message, e.g. that these are from the xtensa HAL originally (so this is a more natural place for them) and that it also resolves the license issue with these being MIT rather than Apache 2 licensed.

Done

**Comment by dcpleung** [comment]
There files do not seem to originate from Xtensa HAL, as these are board specific files. The Xtensa HAL does not have board specific files, but solely dependent on the platform overlay files to dictate how it's being compiled.

**Comment by jhedberg** [comment]
> There files do not seem to originate from Xtensa HAL, as these are board specific files.

@dcpleung these have Tensilica copyright in them, so where do they come from then? Do you have another proposal, since we're aiming to have only Apache 2 licensed content in the main tree, whereas the subtrees (like the HAL one) are more flexible and can easily contain BSD or MIT licensed content.

**Comment by dcpleung** [comment]
These files probably come from the processor support package from Tensilica when a new SoC configuration is uploaded to their server for tools generation (e.g. toolchain, overlay, header files, etc.).

Besides, AFAIK, MIT is compatible with Apache 2.0. I am not totally sure about including MIT licensed files within master. @nashif should know more about this.

**Comment by jhedberg** [comment]
@dcpleung the licenses are indeed compatible, however the main tree's CI blocks the merge (requires an exception to be made) for anything that's not Apache 2. In my earlier talks with @nashif he was suggesting to find ways to avoid having to make such an exception, primarily by moving the files out from the main tree.

**Comment by dcpleung** [comment]
I wonder if we can use the existing `arch/xtensa/core/startup/reset-vector.S` so there is no need for another one.

**Comment by jhedberg** [comment]
> I wonder if we can use the existing arch/xtensa/core/startup/reset-vector.S so there is no need for another one.

@dcpleung what about `_vectors.S`? It has some similarities with `arch/xtensa/core/xtensa-asm2-util.S` but the latter has lots more stuff. Anyway, if there are these existing generic startup code files in the tree, we should definitely use them if possible (not just because of the license issue).

**Comment by finikorg** [comment]
For the 'reset-vector.S` I can use following change to make it working:
```
iff --git a/arch/xtensa/core/startup/reset-vector.S b/arch/xtensa/core/startup/reset-vector.S
index 31877614cc..0c711bca7c 100644
--- a/arch/xtensa/core/startup/reset-vector.S
+++ b/arch/xtensa/core/startup/reset-vector.S
@@ -24,8 +24,10 @@
        .section                .ResetVector.text, "ax"
 
        .align  4
+       .global _ResetVector
        .global __start
 __start:
+_ResetVector:
 
 #if (!XCHAL_HAVE_HALT || defined(XTOS_UNPACK)) && XCHAL_HAVE_IMEM_LOADSTORE
        /*
```

**Pull request closed without merging**
