### PR TITLE
Add SOC overlay for the 2 DSP of NXP i.MXRT700

### PR DESCRIPTION
**Pull request by iuliana-prodan**
The i.MX RT700 has a Compute Subsystem which includes a primary ARM Cortex-M33 running at 325 MHz and Cadence Tensilica HiFi 4 DSP.
It also features an ultra-low power Sense Subsystem which includes a second ARM Cortex-M33 and Cadence Tensilica HiFi 1 DSP.

This pull request adds the SOC overlay for HiFi1 and HiFi4 cores.

### CODE REVIEW

**Comment by iuliana-prodan** [comment]
@nashif @dcpleung can you please have a look on this?

**Comment by dcpleung** [comment]
Could you remove the `key.h` files in both commits?

**Comment by iuliana-prodan** [comment]
> Could you remove the `key.h` files in both commits?

I removed them.

**Comment by iuliana-prodan** [comment]
> > Could you remove the `key.h` files in both commits?
> 
> I removed them.

@dcpleung I have no idea how to fix the CI failure: https://github.com/zephyrproject-rtos/hal_xtensa/actions/runs/11488673050/job/31975891667?pr=31#step:1:36  :(

**Comment by dcpleung** [comment]
https://github.com/zephyrproject-rtos/hal_xtensa/pull/32 is fixing that.

**Review by dcpleung — APPROVED** [review]

**Comment by iuliana-prodan** [comment]
> #32 is fixing that.

Great, thank you!

**Comment by dcpleung** [comment]
That is just merged. Could you rebase? That should allow CI to run.

**Pull request merged**
