### PR TITLE
zephyr: add soc overlay for i.MX8QM and i.MX8QXP

### PR DESCRIPTION
**Pull request by LaurentiuM1234**
Since the i.MX8 Zephyr SoC will be split into two SoCs: mimx8qm6 and mimx8qx6, the xtensa HAL needs to provide two different overlays with the same name as the SoCs. As such, this commit takes the files from the nxp_imx8 SoC and duplicates them, resulting in the creation of mimx8qm6 and mimx8qx6.

As a sidenote: we can/should remove the nxp_imx8 entry once the Zephyr changes have been merged.

**IMPORTANT**: there's no difference between the files found in `nxp_imx8`, `mimx8qm6`, and `mimx8qx6`.

### CODE REVIEW

**Review by iuliana-prodan — APPROVED** [review]

**Review by mmahadevan108 — APPROVED** [review]

**Comment by dcpleung** [comment]
Since they are using the same overlay, I would assume they are both using the same toolchain. If that is the case, you can do a SoC series and use `CONFIG_SOC_TOOLCHAIN_NAME` as the directory name. As long as there is no `CONFIG_SOC_NAME` (which should not be set if doing SoC series), `CONFIG_SOC_TOOLCHAIN_NAME` would be used to construct the path.

**Comment by LaurentiuM1234** [comment]
> Since they are using the same overlay, I would assume they are both using the same toolchain. If that is the case, you can do a SoC series and use `CONFIG_SOC_TOOLCHAIN_NAME` as the directory name. As long as there is no `CONFIG_SOC_NAME` (which should not be set if doing SoC series), `CONFIG_SOC_TOOLCHAIN_NAME` would be used to construct the path.

You're right, they are using the same toolchain. Unfortunately, I can't get rid of `CONFIG_SOC` since this is used to fetch the NXP HAL files for the 2 SoCs it represents: i.MX8QM and i.MX8QXP. Luckily enough, if a SoC overlay with the `CONFIG_SOC` name cannot be found, Zephyr will look for an overlay with the toolchain name. As such, all we need to do here is change `nxp_imx8` to `nxp_imx_adsp`. I've updated the PR accordingly.

**Review by dcpleung — APPROVED** [review]

**Comment by LaurentiuM1234** [comment]
@mmahadevan108 I think this should be ready for merge

**Review by dbaluta — APPROVED** [review]

**Comment by iuliana-prodan** [comment]
@dcpleung @nashif can you please merge this.
Thank you!

**Pull request merged**
