### PR TITLE
Xtensa Intel HAL SoC overlays from SOF project

### PR DESCRIPTION
**Pull request by lgirdwood**
This PR adds support for the Intel Baytrail, Cherrytrail, Braswell, Broadwell, Cannonlake and Icelake derived Audio DSP platforms.

### CODE REVIEW

**Review by dcpleung — APPROVED** [review]
These files are from Tensilica to enable building the HAL for each SoC.

**Comment by galak** [comment]
Mark this pending until we have PRs on the Zephyr side that uses this.

**Review by galak — CHANGES_REQUESTED** [review]
Marking this request changes until there are PRs on Zephyr side that uses this.

**Comment by lgirdwood** [comment]
@galak we should have some PR's for some of the platform next week. The CNL and ICL parts require some rework of the existing upstream ADSP SoC code (S1000 and APL) to move common logic into a common directory (as each IP version is incremental over the last).

**Comment by galak** [comment]
> @galak we should have some PR's for some of the platform next week. The CNL and ICL parts require some rework of the existing upstream ADSP SoC code (S1000 and APL) to move common logic into a common directory (as each IP version is incremental over the last).

No worries, just a process thing.  On the Zephyr side you can modify 'west.yml' to point to the PR and we utilize that to test things are working before merging the changes to the module.

**Comment by nashif** [comment]
> No worries, just a process thing. On the Zephyr side you can modify 'west.yml' to point to the PR and we utilize that to test things are working before merging the changes to the module.

this most likely would also require the new sdk variants...

**Review by nashif — APPROVED** [review]

**Comment by dcpleung** [comment]
A new module will be created for all the SOF stuff. So closing this one...

**Comment by dcpleung** [comment]
Misunderstanding... this is still needed.

**Comment by lgirdwood** [comment]
@andyross @nashif fyi this may still be needed.

**Comment by nashif** [comment]
@lrgirdwo 

> @andyross @nashif fyi this may still be needed.

right, but we are using the wrong naming here, in the related PR to the zephyr tree we are looking for `../../modules/hal/xtensa/zephyr/soc/intel_cavs_20` etc.

**Comment by lgirdwood** [comment]
> @lrgirdwo
> 
> > @andyross @nashif fyi this may still be needed.
> 
> right, but we are using the wrong naming here, in the related PR to the zephyr tree we are looking for `../../modules/hal/xtensa/zephyr/soc/intel_cavs_20` etc.

@nashif Ack, it will need @andyross or @lyakh to upate paths to align with the upstream branch. Will close this once another PR is ready.

**Comment by dcpleung** [comment]
None of these are supported in the main Zephyr tree anymore. So there is no need to these overlays. Closing...

**Pull request closed without merging**
