### PR TITLE
zephyr: rename SoC overlay for NXP i.MX8MP

### PR DESCRIPTION
**Pull request by iuliana-prodan**
Rename SoC overlay for NXP i.MX8MP from nxp_imx8m
to mimx8ml8.

This is needed in order to enable, for DSP, for now, the UART console and use the driver from NXP hal.
With this name, the driver is added directly from
hal/nxp/mcux/mcux-sdk/devices/MIMX8ML8.

### CODE REVIEW

**Comment by iuliana-prodan** [comment]
@nashif can you please help me with this PR.
I still don't have rights to add reviewers. 
Thanks!

cc: @dbaluta @dleach02

**Review by dbaluta — APPROVED** [review]

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
@dcpleung   can you please have a look.

We reverted your patch https://github.com/zephyrproject-rtos/hal_xtensa/commit/e636ce8fdf334addaae37fb2417dc2cb8bf7b50a because it looks like there is no available toolchain compatible with your patch.

**Comment by iuliana-prodan** [comment]
@dcpleung @nashif can we update xtensa hal? 
I see that [zephyr-sdk-0.16.](https://github.com/zephyrproject-rtos/sdk-ng/releases) has support for xtensa-intel_ace15_mtpm_zephyr-elf. 
Can we  use now the commit https://github.com/zephyrproject-rtos/hal_xtensa/commit/e636ce8fdf334addaae37fb2417dc2cb8bf7b50a?

**Comment by iuliana-prodan** [comment]
> @dcpleung @nashif can we update xtensa hal? I see that [zephyr-sdk-0.16.](https://github.com/zephyrproject-rtos/sdk-ng/releases) has support for xtensa-intel_ace15_mtpm_zephyr-elf. Can we use now the commit [e636ce8](https://github.com/zephyrproject-rtos/hal_xtensa/commit/e636ce8fdf334addaae37fb2417dc2cb8bf7b50a)?

@lrgirdwo @galak @dleach02 @aborisovich @dcpleung @henrikbrixandersen please, help me with a review! 
This is pending for 2 weeks

Also, this is a dependency for https://github.com/zephyrproject-rtos/zephyr/pull/57084

**Comment by dleach02** [comment]
@nashif, can you (or someone from Intel) review the changes here?

**Comment by nashif** [comment]
Can you please clarify why you are reverting some intel soc related changes?

**Review by nashif — APPROVED** [review]

**Comment by iuliana-prodan** [comment]
> Can you please clarify why you are reverting some intel soc related changes?

Hi @nashif 
Please, see:
https://github.com/zephyrproject-rtos/zephyr/pull/57084#issuecomment-1517614927
and
https://github.com/zephyrproject-rtos/zephyr/pull/57084#issuecomment-1518092809

But, as I mentioned above, I see that [zephyr-sdk-0.16.](https://github.com/zephyrproject-rtos/sdk-ng/releases) has support for xtensa-intel_ace15_mtpm_zephyr-elf.
Can we use now the commit https://github.com/zephyrproject-rtos/hal_xtensa/commit/e636ce8fdf334addaae37fb2417dc2cb8bf7b50a?

**Comment by iuliana-prodan** [comment]
@nashif Thanks for merging this. 
Can I now use the latest commit id in west.yaml from Zephyr to update xtensa_hal - in PR: https://github.com/zephyrproject-rtos/zephyr/pull/57084?

**Comment by henrikbrixandersen** [comment]
> @nashif Thanks for merging this.
> Can I now use the latest commit id in west.yaml from Zephyr to update xtensa_hal - in PR: [zephyrproject-rtos/zephyr#57084](https://github.com/zephyrproject-rtos/zephyr/pull/57084)?

Yes :)

**Comment by iuliana-prodan** [comment]
> > @nashif Thanks for merging this.
> > Can I now use the latest commit id in west.yaml from Zephyr to update xtensa_hal - in PR: [zephyrproject-rtos/zephyr#57084](https://github.com/zephyrproject-rtos/zephyr/pull/57084)?
> 
> Yes :)

Done https://github.com/zephyrproject-rtos/zephyr/pull/57084/commits/d5e323274da919f259ebd94c8880062ff5c98b45

**Pull request merged**
